# Generated by Django 4.2.30 on 2026-04-17 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("met_developer", models.URLField(blank=True, null=True)),
                ("message", models.TextField()),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "permission_to_publish",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("yes_anonymous", "Yes, publish anonymously"),
                            ("no", "No"),
                        ],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "testimonial_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="testimonial_images/"
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
    ]
