# Generated by Django 4.2.30 on 2026-04-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testimonial", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="met_developer",
        ),
    ]
