# Generated by Django 4.2.30 on 2026-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonial", "0002_remove_testimonial_met_developer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="permission_to_publish",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
    ]
