# Generated by Django 4.2.30 on 2026-04-24 11:01

from django.db import migrations
import django_resized.forms
import testimonial.models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonial", "0003_alter_testimonial_permission_to_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="testimonial_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=testimonial.models.default_image,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[300, 300],
                upload_to="testimonial_images/",
            ),
        ),
    ]
