# Generated by Django 4.2.30 on 2026-05-07 12:37

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("testimonial", "0004_alter_testimonial_testimonial_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="message",
            field=froala_editor.fields.FroalaField(),
        ),
    ]
