# Generated by Django 4.2.30 on 2026-05-07 13:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonial", "0005_alter_testimonial_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="message",
            field=tinymce.models.HTMLField(),
        ),
    ]
