# Generated by Django 4.2.30 on 2026-05-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonial", "0006_alter_testimonial_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
