# Generated by Django 4.2.30 on 2026-04-24 11:01

import accounts.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=accounts.models.default_image,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[300, 300],
                upload_to="profile_images/",
            ),
        ),
    ]
