# Generated by Django 4.2.30 on 2026-05-02 00:29

import accounts.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=accounts.models.default_image, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=[300, 300], upload_to='profile_images/'),
        ),
    ]
