# Generated by Django 4.2.30 on 2026-04-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_category_created_at_alter_portfolio_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="github_link",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="client",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
