# Generated by Django 4.2.30 on 2026-04-24 11:01

from django.db import migrations
import django_resized.forms
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_remove_portfolio_github_link_portfolio_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="image1",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=portfolio.models.default_image,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[300, 300],
                upload_to="portfolio_images/",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image2",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=portfolio.models.default_image,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[300, 300],
                upload_to="portfolio_images/",
            ),
        ),
    ]
