# Generated by Django 4.2.30 on 2026-05-07 12:37

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_portfolio_image1_alter_portfolio_image2"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="infrastructure",
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=froala_editor.fields.FroalaField(),
        ),
    ]
