# Generated by Django 4.2.30 on 2026-05-07 13:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_portfolio_infrastructure_alter_portfolio_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="infrastructure",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
