# Generated by Django 4.2.30 on 2026-05-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_portfolio_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="infrastructure",
            field=models.TextField(blank=True, null=True),
        ),
    ]
